name: CI Test Permissions Reusable
on:
  workflow_call:
jobs:
  test-with-permissions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Hello
        run: echo "permissions work"