name: CI Test Defaults Reusable
on:
  workflow_call:
jobs:
  test-with-defaults:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Hello
        run: echo "defaults work"