name: CI Pipeline

on:
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/**"
  push:
    branches:
      - master
    paths:
      - ".github/workflows/**"

jobs:
  validation:
    uses: ./.github/workflows/ci-minimal-test.yml